// <auto-generated />
using System;
using Employee.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230908060321_employee001")]
    partial class employee001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee.Model.tblEmployee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("employeeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("employeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("employeeSalary")
                        .HasColumnType("int");

                    b.Property<int>("supervisorId")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.ToTable("tblEmployees");
                });

            modelBuilder.Entity("Employee.Model.tblEmployeeAttendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("isAbsent")
                        .HasColumnType("int");

                    b.Property<int>("isOffday")
                        .HasColumnType("int");

                    b.Property<int>("isPresent")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemployeeId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("tblEmployeeemployeeId");

                    b.ToTable("tblEmployeeAttendances");
                });

            modelBuilder.Entity("Employee.Model.tblEmployeeAttendance", b =>
                {
                    b.HasOne("Employee.Model.tblEmployee", "tblEmployee")
                        .WithMany("tblEmployeeAttendances")
                        .HasForeignKey("tblEmployeeemployeeId");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Employee.Model.tblEmployee", b =>
                {
                    b.Navigation("tblEmployeeAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
